name: Build tetrad

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build release
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DLL
          path: |
            target/release/dcs_tetrad.dll
            target/release/dcs_tetrad.pdb
            lua/DCS/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            target/release/dcs_tetrad.dll
            target/release/dcs_tetrad.pdb
            lua/DCS/*
